//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamEngine.CompiledScripts {
	using System;
	using System.Collections;
	using System.Collections.Generic;
	using SteamEngine;
	using SteamEngine.Timers;
	using SteamEngine.Packets;
	using SteamEngine.Persistence;
	using SteamEngine.Common;
	
	
	public partial class DiscordanceEffectPluginDef : TimerPluginDef {
		
		public DiscordanceEffectPluginDef(String defname, String filename, Int32 headerLine) : 
				base(defname, filename, headerLine) {
		}
		
		protected override SteamEngine.Plugin CreateImpl() {
			return new DiscordanceEffectPlugin();
		}
		
		public new static void Bootstrap() {
			SteamEngine.PluginDef.RegisterPluginDef(typeof(DiscordanceEffectPluginDef), typeof(DiscordanceEffectPlugin));
		}
	}
	
	[SteamEngine.DeepCopyableClassAttribute()]
	[SteamEngine.Persistence.SaveableClassAttribute()]
	public partial class DiscordanceEffectPlugin : TimerPlugin {
		
		public Int32 discordEffectPower = 0;
		
		public Int16 lowed_dex = 0;
		
		public Int16 lowed_str = 0;
		
		public Int16 lowed_int = 0;
		
		public Int16 lowed_hits = 0;
		
		public Int16 lowed_mana = 0;
		
		public Int16 lowed_stam = 0;
		
		public UInt16 lowed_magery = 0;
		
		public UInt16 lowed_resist = 0;
		
		public UInt16 lowed_wrestl = 0;
		
		public UInt16 lowed_archer = 0;
		
		public UInt16 lowed_mace = 0;
		
		public UInt16 lowed_onehand = 0;
		
		public UInt16 lowed_twohand = 0;
		
		public UInt16 lowed_poison = 0;
		
		public UInt16 lowed_ei = 0;
		
		[SteamEngine.DeepCopyImplementationAttribute()]
		public DiscordanceEffectPlugin(DiscordanceEffectPlugin copyFrom) : 
				base(copyFrom) {
			this.discordEffectPower = copyFrom.discordEffectPower;
			this.lowed_dex = copyFrom.lowed_dex;
			this.lowed_str = copyFrom.lowed_str;
			this.lowed_int = copyFrom.lowed_int;
			this.lowed_hits = copyFrom.lowed_hits;
			this.lowed_mana = copyFrom.lowed_mana;
			this.lowed_stam = copyFrom.lowed_stam;
			this.lowed_magery = copyFrom.lowed_magery;
			this.lowed_resist = copyFrom.lowed_resist;
			this.lowed_wrestl = copyFrom.lowed_wrestl;
			this.lowed_archer = copyFrom.lowed_archer;
			this.lowed_mace = copyFrom.lowed_mace;
			this.lowed_onehand = copyFrom.lowed_onehand;
			this.lowed_twohand = copyFrom.lowed_twohand;
			this.lowed_poison = copyFrom.lowed_poison;
			this.lowed_ei = copyFrom.lowed_ei;
		}
		
		[SteamEngine.Persistence.LoadingInitializerAttribute()]
		public DiscordanceEffectPlugin() {
		}
		
		private new DiscordanceEffectPluginDef Def {
			get {
				return ((DiscordanceEffectPluginDef)(this.Def));
			}
		}
		
		[SteamEngine.Persistence.SaveAttribute()]
		public override void Save(SaveStream output) {
			if ((this.discordEffectPower != 0)) {
				output.WriteValue("discordEffectPower", this.discordEffectPower);
			}
			if ((this.lowed_dex != 0)) {
				output.WriteValue("lowed_dex", this.lowed_dex);
			}
			if ((this.lowed_str != 0)) {
				output.WriteValue("lowed_str", this.lowed_str);
			}
			if ((this.lowed_int != 0)) {
				output.WriteValue("lowed_int", this.lowed_int);
			}
			if ((this.lowed_hits != 0)) {
				output.WriteValue("lowed_hits", this.lowed_hits);
			}
			if ((this.lowed_mana != 0)) {
				output.WriteValue("lowed_mana", this.lowed_mana);
			}
			if ((this.lowed_stam != 0)) {
				output.WriteValue("lowed_stam", this.lowed_stam);
			}
			if ((this.lowed_magery != 0)) {
				output.WriteValue("lowed_magery", this.lowed_magery);
			}
			if ((this.lowed_resist != 0)) {
				output.WriteValue("lowed_resist", this.lowed_resist);
			}
			if ((this.lowed_wrestl != 0)) {
				output.WriteValue("lowed_wrestl", this.lowed_wrestl);
			}
			if ((this.lowed_archer != 0)) {
				output.WriteValue("lowed_archer", this.lowed_archer);
			}
			if ((this.lowed_mace != 0)) {
				output.WriteValue("lowed_mace", this.lowed_mace);
			}
			if ((this.lowed_onehand != 0)) {
				output.WriteValue("lowed_onehand", this.lowed_onehand);
			}
			if ((this.lowed_twohand != 0)) {
				output.WriteValue("lowed_twohand", this.lowed_twohand);
			}
			if ((this.lowed_poison != 0)) {
				output.WriteValue("lowed_poison", this.lowed_poison);
			}
			if ((this.lowed_ei != 0)) {
				output.WriteValue("lowed_ei", this.lowed_ei);
			}
			base.Save(output);
		}
		
		[SteamEngine.Persistence.LoadLineAttribute()]
		public override void LoadLine(string filename, int line, string prop, string value) {
			switch (prop) {

				case "discordeffectpower":
			this.discordEffectPower = SteamEngine.Common.ConvertTools.ParseInt32(value);
					break;

				case "lowed_dex":
			this.lowed_dex = SteamEngine.Common.ConvertTools.ParseInt16(value);
					break;

				case "lowed_str":
			this.lowed_str = SteamEngine.Common.ConvertTools.ParseInt16(value);
					break;

				case "lowed_int":
			this.lowed_int = SteamEngine.Common.ConvertTools.ParseInt16(value);
					break;

				case "lowed_hits":
			this.lowed_hits = SteamEngine.Common.ConvertTools.ParseInt16(value);
					break;

				case "lowed_mana":
			this.lowed_mana = SteamEngine.Common.ConvertTools.ParseInt16(value);
					break;

				case "lowed_stam":
			this.lowed_stam = SteamEngine.Common.ConvertTools.ParseInt16(value);
					break;

				case "lowed_magery":
			this.lowed_magery = SteamEngine.Common.ConvertTools.ParseUInt16(value);
					break;

				case "lowed_resist":
			this.lowed_resist = SteamEngine.Common.ConvertTools.ParseUInt16(value);
					break;

				case "lowed_wrestl":
			this.lowed_wrestl = SteamEngine.Common.ConvertTools.ParseUInt16(value);
					break;

				case "lowed_archer":
			this.lowed_archer = SteamEngine.Common.ConvertTools.ParseUInt16(value);
					break;

				case "lowed_mace":
			this.lowed_mace = SteamEngine.Common.ConvertTools.ParseUInt16(value);
					break;

				case "lowed_onehand":
			this.lowed_onehand = SteamEngine.Common.ConvertTools.ParseUInt16(value);
					break;

				case "lowed_twohand":
			this.lowed_twohand = SteamEngine.Common.ConvertTools.ParseUInt16(value);
					break;

				case "lowed_poison":
			this.lowed_poison = SteamEngine.Common.ConvertTools.ParseUInt16(value);
					break;

				case "lowed_ei":
			this.lowed_ei = SteamEngine.Common.ConvertTools.ParseUInt16(value);
					break;

				default:

			base.LoadLine(filename, line, prop, value);
					break;
			}
		}
	}
}
