//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamEngine.CompiledScripts {
	using System;
	using System.Collections;
	using System.Collections.Generic;
	using SteamEngine;
	using SteamEngine.Timers;
	using SteamEngine.Packets;
	using SteamEngine.Persistence;
	using SteamEngine.Common;
	
	
	public partial class WarcryEffectPluginDef : TimerPluginDef {
		
		public WarcryEffectPluginDef(String defname, String filename, Int32 headerLine) : 
				base(defname, filename, headerLine) {
		}
		
		protected override SteamEngine.Plugin CreateImpl() {
			return new WarcryEffectPlugin();
		}
		
		public new static void Bootstrap() {
			SteamEngine.PluginDef.RegisterPluginDef(typeof(WarcryEffectPluginDef), typeof(WarcryEffectPlugin));
		}
	}
	
	[SteamEngine.DeepCopyableClassAttribute()]
	[SteamEngine.Persistence.SaveableClassAttribute()]
	public partial class WarcryEffectPlugin : TimerPlugin {
		
		[SteamEngine.DeepCopyImplementationAttribute()]
		public WarcryEffectPlugin(WarcryEffectPlugin copyFrom) : 
				base(copyFrom) {
		}
		
		[SteamEngine.Persistence.LoadingInitializerAttribute()]
		public WarcryEffectPlugin() {
		}
		
		public new WarcryEffectPluginDef TypeDef {
			get {
				return ((WarcryEffectPluginDef)(base.Def));
			}
		}
	}
}
