//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamEngine.CompiledScripts {
	using System;
	using System.Collections;
	using System.Collections.Generic;
	using SteamEngine;
	using SteamEngine.Timers;
	using SteamEngine.Persistence;
	using SteamEngine.Common;
	
	
	public partial class PlayerVendorDef : NPCDef {
		
		public PlayerVendorDef(String defname, String filename, Int32 headerLine) : 
				base(defname, filename, headerLine) {
		}
		
		protected override SteamEngine.Thing CreateImpl() {
			return new PlayerVendor(this);
		}
		
		public new static void Bootstrap() {
			SteamEngine.ThingDef.RegisterThingDef(typeof(PlayerVendorDef), typeof(PlayerVendor));
		}
	}
	
	[SteamEngine.DeepCopyableClassAttribute()]
	[SteamEngine.Persistence.SaveableClassAttribute()]
	public partial class PlayerVendor : NPC {
		
		[SteamEngine.DeepCopyImplementationAttribute()]
		public PlayerVendor(PlayerVendor copyFrom) : 
				base(copyFrom) {
		}
		
		public PlayerVendor(PlayerVendorDef myDef) : 
				base(myDef) {
		}
		
		public new PlayerVendorDef TypeDef {
			get {
				return ((PlayerVendorDef)(base.Def));
			}
		}
	}
	
	public partial class PlayerVendorStockEntryDef : ContainerDef {
		
		public PlayerVendorStockEntryDef(String defname, String filename, Int32 headerLine) : 
				base(defname, filename, headerLine) {
		}
		
		protected override SteamEngine.Thing CreateImpl() {
			return new PlayerVendorStockEntry(this);
		}
		
		public new static void Bootstrap() {
			SteamEngine.ThingDef.RegisterThingDef(typeof(PlayerVendorStockEntryDef), typeof(PlayerVendorStockEntry));
		}
	}
	
	[SteamEngine.DeepCopyableClassAttribute()]
	[SteamEngine.Persistence.SaveableClassAttribute()]
	public partial class PlayerVendorStockEntry : Container {
		
		Decimal price = 0;
		
		Boolean isCategory = false;
		
		Boolean soldByUnits = false;
		
		[SteamEngine.DeepCopyImplementationAttribute()]
		public PlayerVendorStockEntry(PlayerVendorStockEntry copyFrom) : 
				base(copyFrom) {
			this.price = copyFrom.price;
			this.isCategory = copyFrom.isCategory;
			this.soldByUnits = copyFrom.soldByUnits;
		}
		
		public PlayerVendorStockEntry(PlayerVendorStockEntryDef myDef) : 
				base(myDef) {
		}
		
		public new PlayerVendorStockEntryDef TypeDef {
			get {
				return ((PlayerVendorStockEntryDef)(base.Def));
			}
		}
		
		public override void Save(SaveStream output) {
			if ((this.price != 0)) {
				output.WriteValue("price", this.price);
			}
			if ((this.isCategory != false)) {
				output.WriteValue("isCategory", this.isCategory);
			}
			if ((this.soldByUnits != false)) {
				output.WriteValue("soldByUnits", this.soldByUnits);
			}
			base.Save(output);
		}
		
		public override void LoadLine(string filename, int line, string valueName, string valueString) {
			switch (valueName) {

				case "price":
			this.price = SteamEngine.Common.ConvertTools.ParseDecimal(valueString);
					break;

				case "iscategory":
			this.isCategory = SteamEngine.Common.ConvertTools.ParseBoolean(valueString);
					break;

				case "soldbyunits":
			this.soldByUnits = SteamEngine.Common.ConvertTools.ParseBoolean(valueString);
					break;

				default:

			base.LoadLine(filename, line, valueName, valueString);
					break;
			}
		}
	}
}
