//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.1
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamEngine.CompiledScripts {
	using System;
	using System.Collections;
	using System.Collections.Generic;
	using SteamEngine;
	using SteamEngine.Timers;
	using SteamEngine.Persistence;
	using SteamEngine.Common;
	
	
	public partial class PlayerVendorDef : NPCDef {
		
		public PlayerVendorDef(String defname, String filename, Int32 headerLine) : 
				base(defname, filename, headerLine) {
		}
		
		protected override SteamEngine.Thing CreateImpl() {
			return new PlayerVendor(this);
		}
		
		public new static void Bootstrap() {
			SteamEngine.ThingDef.RegisterThingDef(typeof(PlayerVendorDef), typeof(PlayerVendor));
		}
	}
	
	[SteamEngine.DeepCopyableClassAttribute()]
	[SteamEngine.Persistence.SaveableClassAttribute()]
	public partial class PlayerVendor : NPC {
		
		[SteamEngine.DeepCopyImplementationAttribute()]
		public PlayerVendor(PlayerVendor copyFrom) : 
				base(copyFrom) {
		}
		
		public PlayerVendor(PlayerVendorDef myDef) : 
				base(myDef) {
		}
		
		public new PlayerVendorDef TypeDef {
			get {
				return ((PlayerVendorDef)(base.Def));
			}
		}
	}
}
