//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamEngine.CompiledScripts {
	using System;
	using System.Collections;
	using System.Collections.Generic;
	using SteamEngine;
	using SteamEngine.Timers;
	using SteamEngine.Persistence;
	using SteamEngine.Common;
	
	
	public partial class ShiningItemDef : EquippableDef {
		
		public ShiningItemDef(String defname, String filename, Int32 headerLine) : 
				base(defname, filename, headerLine) {
		}
		
		protected override SteamEngine.Thing CreateImpl() {
			return new ShiningItem(this);
		}
		
		public new static void Bootstrap() {
			SteamEngine.ThingDef.RegisterThingDef(typeof(ShiningItemDef), typeof(ShiningItem));
		}
	}
	
	[SteamEngine.DeepCopyableClassAttribute()]
	[SteamEngine.Persistence.SaveableClassAttribute()]
	public partial class ShiningItem : Equippable {
		
		[SteamEngine.DeepCopyImplementationAttribute()]
		public ShiningItem(ShiningItem copyFrom) : 
				base(copyFrom) {
		}
		
		public ShiningItem(ShiningItemDef myDef) : 
				base(myDef) {
		}
		
		public new ShiningItemDef TypeDef {
			get {
				return ((ShiningItemDef)(base.Def));
			}
		}
	}
}
