//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:2.0.50727.3603
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamEngine.CompiledScripts {
	using System;
	using System.Collections;
	using System.Collections.Generic;
	using SteamEngine;
	using SteamEngine.Timers;
	using SteamEngine.Persistence;
	using SteamEngine.Common;
	
	
	public partial class ManaShieldPluginDef : StatDrainingEffectDurationPluginDef {
		
		public ManaShieldPluginDef(String defname, String filename, Int32 headerLine) : 
				base(defname, filename, headerLine) {
		}
		
		protected override SteamEngine.Plugin CreateImpl() {
			return new ManaShieldPlugin();
		}
		
		public new static void Bootstrap() {
			SteamEngine.PluginDef.RegisterPluginDef(typeof(ManaShieldPluginDef), typeof(ManaShieldPlugin));
		}
	}
	
	[SteamEngine.DeepCopyableClassAttribute()]
	[SteamEngine.Persistence.SaveableClassAttribute()]
	public partial class ManaShieldPlugin : StatDrainingEffectDurationPlugin {
		
		[SteamEngine.DeepCopyImplementationAttribute()]
		public ManaShieldPlugin(ManaShieldPlugin copyFrom) : 
				base(copyFrom) {
		}
		
		[SteamEngine.Persistence.LoadingInitializerAttribute()]
		public ManaShieldPlugin() {
		}
		
		public new ManaShieldPluginDef TypeDef {
			get {
				return ((ManaShieldPluginDef)(base.Def));
			}
		}
	}
}
