//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:2.0.50727.4927
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamEngine.CompiledScripts {
	using System;
	using System.Collections;
	using System.Collections.Generic;
	using SteamEngine;
	using SteamEngine.Timers;
	using SteamEngine.Persistence;
	using SteamEngine.Common;
	
	
	public partial class IgnitionActivatedPluginDef : StatDrainingEffectDurationPluginDef {
		
		public IgnitionActivatedPluginDef(String defname, String filename, Int32 headerLine) : 
				base(defname, filename, headerLine) {
		}
		
		protected override SteamEngine.Plugin CreateImpl() {
			return new IgnitionActivatedPlugin();
		}
		
		public new static void Bootstrap() {
			SteamEngine.PluginDef.RegisterPluginDef(typeof(IgnitionActivatedPluginDef), typeof(IgnitionActivatedPlugin));
		}
	}
	
	[SteamEngine.DeepCopyableClassAttribute()]
	[SteamEngine.Persistence.SaveableClassAttribute()]
	public partial class IgnitionActivatedPlugin : StatDrainingEffectDurationPlugin {
		
		[SteamEngine.DeepCopyImplementationAttribute()]
		public IgnitionActivatedPlugin(IgnitionActivatedPlugin copyFrom) : 
				base(copyFrom) {
		}
		
		[SteamEngine.Persistence.LoadingInitializerAttribute()]
		public IgnitionActivatedPlugin() {
		}
		
		public new IgnitionActivatedPluginDef TypeDef {
			get {
				return ((IgnitionActivatedPluginDef)(base.Def));
			}
		}
	}
	
	public partial class IgnitionEffectPluginDef : EffectDurationPluginDef {
		
		public IgnitionEffectPluginDef(String defname, String filename, Int32 headerLine) : 
				base(defname, filename, headerLine) {
		}
		
		protected override SteamEngine.Plugin CreateImpl() {
			return new IgnitionEffectPlugin();
		}
		
		public new static void Bootstrap() {
			SteamEngine.PluginDef.RegisterPluginDef(typeof(IgnitionEffectPluginDef), typeof(IgnitionEffectPlugin));
		}
	}
	
	[SteamEngine.DeepCopyableClassAttribute()]
	[SteamEngine.Persistence.SaveableClassAttribute()]
	public partial class IgnitionEffectPlugin : EffectDurationPlugin {
		
		[SteamEngine.DeepCopyImplementationAttribute()]
		public IgnitionEffectPlugin(IgnitionEffectPlugin copyFrom) : 
				base(copyFrom) {
		}
		
		[SteamEngine.Persistence.LoadingInitializerAttribute()]
		public IgnitionEffectPlugin() {
		}
		
		public new IgnitionEffectPluginDef TypeDef {
			get {
				return ((IgnitionEffectPluginDef)(base.Def));
			}
		}
	}
}
