//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:2.0.50727.3603
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamEngine.CompiledScripts {
	using System;
	using System.Collections;
	using System.Collections.Generic;
	using SteamEngine;
	using SteamEngine.Timers;
	using SteamEngine.Persistence;
	using SteamEngine.Common;
	
	
	public partial class SpellSchoolManaDiscountPluginDef : EffectDurationPluginDef {
		
		private FieldValue spellSchool;
		
		public SpellSchoolManaDiscountPluginDef(String defname, String filename, Int32 headerLine) : 
				base(defname, filename, headerLine) {
			this.spellSchool = this.InitTypedField("spellSchool", (DamageType) 0, typeof(DamageType));
		}
		
		public DamageType SpellSchool {
			get {
				return ((DamageType)(this.spellSchool.CurrentValue));
			}
			set {
				this.spellSchool.CurrentValue = value;
			}
		}
		
		protected override SteamEngine.Plugin CreateImpl() {
			return new SpellSchoolManaDiscountPlugin();
		}
		
		public new static void Bootstrap() {
			SteamEngine.PluginDef.RegisterPluginDef(typeof(SpellSchoolManaDiscountPluginDef), typeof(SpellSchoolManaDiscountPlugin));
		}
	}
	
	[SteamEngine.DeepCopyableClassAttribute()]
	[SteamEngine.Persistence.SaveableClassAttribute()]
	public partial class SpellSchoolManaDiscountPlugin : EffectDurationPlugin {
		
		[SteamEngine.DeepCopyImplementationAttribute()]
		public SpellSchoolManaDiscountPlugin(SpellSchoolManaDiscountPlugin copyFrom) : 
				base(copyFrom) {
		}
		
		[SteamEngine.Persistence.LoadingInitializerAttribute()]
		public SpellSchoolManaDiscountPlugin() {
		}
		
		public new SpellSchoolManaDiscountPluginDef TypeDef {
			get {
				return ((SpellSchoolManaDiscountPluginDef)(base.Def));
			}
		}
	}
}
