//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:2.0.50727.3603
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamEngine.CompiledScripts {
	using System;
	using System.Collections;
	using System.Collections.Generic;
	using SteamEngine;
	using SteamEngine.Timers;
	using SteamEngine.Persistence;
	using SteamEngine.Common;
	
	
	public partial class SpellManaDiscountPluginDef : EffectDurationPluginDef {
		
		private FieldValue spell;
		
		public SpellManaDiscountPluginDef(String defname, String filename, Int32 headerLine) : 
				base(defname, filename, headerLine) {
			this.spell = this.InitTypedField("spell", null, typeof(SpellDef));
		}
		
		public SpellDef Spell {
			get {
				return ((SpellDef)(this.spell.CurrentValue));
			}
			set {
				this.spell.CurrentValue = value;
			}
		}
		
		protected override SteamEngine.Plugin CreateImpl() {
			return new SpellManaDiscountPlugin();
		}
		
		public new static void Bootstrap() {
			SteamEngine.PluginDef.RegisterPluginDef(typeof(SpellManaDiscountPluginDef), typeof(SpellManaDiscountPlugin));
		}
	}
	
	[SteamEngine.DeepCopyableClassAttribute()]
	[SteamEngine.Persistence.SaveableClassAttribute()]
	public partial class SpellManaDiscountPlugin : EffectDurationPlugin {
		
		[SteamEngine.DeepCopyImplementationAttribute()]
		public SpellManaDiscountPlugin(SpellManaDiscountPlugin copyFrom) : 
				base(copyFrom) {
		}
		
		[SteamEngine.Persistence.LoadingInitializerAttribute()]
		public SpellManaDiscountPlugin() {
		}
		
		public new SpellManaDiscountPluginDef TypeDef {
			get {
				return ((SpellManaDiscountPluginDef)(base.Def));
			}
		}
	}
}
