//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:2.0.50727.3603
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamEngine.CompiledScripts {
	using System;
	using System.Collections;
	using System.Collections.Generic;
	using SteamEngine;
	using SteamEngine.Timers;
	using SteamEngine.Persistence;
	using SteamEngine.Common;
	
	
	public partial class SpellClassDiscountPluginDef : EffectDurationPluginDef {
		
		private FieldValue spellDefClass;
		
		public SpellClassDiscountPluginDef(String defname, String filename, Int32 headerLine) : 
				base(defname, filename, headerLine) {
			this.spellDefClass = this.InitTypedField("spellDefClass", null, typeof(Type));
		}
		
		public Type SpellDefClass {
			get {
				return ((Type)(this.spellDefClass.CurrentValue));
			}
			set {
				this.spellDefClass.CurrentValue = value;
			}
		}
		
		protected override SteamEngine.Plugin CreateImpl() {
			return new SpellClassDiscountPlugin();
		}
		
		public new static void Bootstrap() {
			SteamEngine.PluginDef.RegisterPluginDef(typeof(SpellClassDiscountPluginDef), typeof(SpellClassDiscountPlugin));
		}
	}
	
	[SteamEngine.DeepCopyableClassAttribute()]
	[SteamEngine.Persistence.SaveableClassAttribute()]
	public partial class SpellClassDiscountPlugin : EffectDurationPlugin {
		
		[SteamEngine.DeepCopyImplementationAttribute()]
		public SpellClassDiscountPlugin(SpellClassDiscountPlugin copyFrom) : 
				base(copyFrom) {
		}
		
		[SteamEngine.Persistence.LoadingInitializerAttribute()]
		public SpellClassDiscountPlugin() {
		}
		
		public new SpellClassDiscountPluginDef TypeDef {
			get {
				return ((SpellClassDiscountPluginDef)(base.Def));
			}
		}
	}
}
