//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamEngine.CompiledScripts {
	using System;
	using System.Collections;
	using System.Collections.Generic;
	using SteamEngine;
	using SteamEngine.Timers;
	using SteamEngine.Packets;
	using SteamEngine.Persistence;
	using SteamEngine.Common;
	
	
	public partial class SpellScrollDef : ItemDef {
		
		public SpellScrollDef(String defname, String filename, Int32 headerLine) : 
				base(defname, filename, headerLine) {
		}
		
		protected override SteamEngine.Thing CreateImpl() {
			return new SpellScroll(this);
		}
		
		public new static void Bootstrap() {
			SteamEngine.ThingDef.RegisterThingDef(typeof(SpellScrollDef), typeof(SpellScroll));
		}
	}
	
	[SteamEngine.DeepCopyableClassAttribute()]
	[SteamEngine.Persistence.SaveableClassAttribute()]
	public partial class SpellScroll : Item {
		
		[SteamEngine.DeepCopyImplementationAttribute()]
		public SpellScroll(SpellScroll copyFrom) : 
				base(copyFrom) {
		}
		
		public SpellScroll(ThingDef myDef) : 
				base(myDef) {
		}
		
		public new SpellScrollDef TypeDef {
			get {
				return ((SpellScrollDef)(base.Def));
			}
		}
	}
}
