/*
	This program is free software; you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation; either version 2 of the License, or
	(at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program; if not, write to the Free Software
	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
	Or visit http://www.gnu.org/copyleft/gpl.html
*/

using System;
using System.CodeDom;
using System.Collections.Generic;
using System.Reflection;
using Shielded;
using SteamEngine.Common;
using SteamEngine.CompiledScripts.Dialogs;
using SteamEngine.Persistence;
using SteamEngine.Scripting.Compilation;

namespace SteamEngine.CompiledScripts {
	internal sealed class ViewableClassGenerator : ISteamCsCodeGenerator {
		//array of special types which (or whose children) will be viewable even if the classes doesn't have the
		//viewable attribute
		static Type[] viewableSpecials = { typeof(Plugin) };

		static List<Type> viewableClasses = new List<Type>();

		//key is type, value is the list of its descriptors
		static Dictionary<Type, List<Type>> viewableDescriptorsForTypes = new Dictionary<Type, List<Type>>();

		//generated instances associated with their real Types - used for hierarchic generating
		static Dictionary<Type, GeneratedInstance> generatedClasses = new Dictionary<Type, GeneratedInstance>();

		internal static int classCounter;

		public CodeCompileUnit WriteSources() {
			try {
				var codeCompileUnit = new CodeCompileUnit();
				if (viewableClasses.Count > 0) {
					Logger.WriteDebug("Generating DataViews and View Descriptors");

					var ns = new CodeNamespace("SteamEngine.CompiledScripts.Dialogs");
					codeCompileUnit.Namespaces.Add(ns);

					//first prepare the GIs for generating - find all fields,properties,buttons to be generated
					foreach (var viewableClass in viewableClasses) {
						try {
							//class for generating all fields, including those from possible descriptors
							var gi = new GeneratedInstance(viewableClass);
							generatedClasses[viewableClass] = gi; //store the generated instance for this type
						} catch (FatalException) {
							throw;
						} catch (TransException) {
							throw;
						} catch (Exception e) {
							Logger.WriteError(viewableClass.Assembly.GetName().Name, viewableClass.Name, e);
							return null;
						}
					}

					//now remove unnecessary fields/properties/buttons being generated by parents and prepare inner classes
					foreach (var oneGI in generatedClasses.Values) {
						oneGI.SetHierarchy();
					}

					//finally generate all classes
					foreach (var oneGI in generatedClasses.Values) {
						try {
							//class for generating all fields, including those from possible descriptors
							if (oneGI.GetAllFieldViewsCount() > 0) {//we have at least one MemberInfo
								var ctd = oneGI.GetGeneratedType();
								ns.Types.Add(ctd);
							}
						} catch (FatalException) {
							throw;
						} catch (TransException) {
							throw;
						} catch (Exception e) {
							Logger.WriteError(oneGI.type.Assembly.GetName().Name, oneGI.type.Name, e);
							return null;
						}
					}
					Logger.WriteDebug("Done generating " + viewableClasses.Count + " DataViews and View Descriptors");
				}
				return codeCompileUnit;
			} finally {
				viewableClasses.Clear();
			}
		}

		public void HandleAssembly(Assembly compiledAssembly) {

		}

		public string FileName {
			get {
				return "ViewableClasses.Generated.cs";
			}
		}

		/// <summary>While loading this class, make some registrations in the ClassManager for handling ViewableClasses</summary>
		public static void Bootstrap() {
			//register the CheckViewabilityClass method so every ClassManager managed Type will be
			//checked here for its Viewability...
			if (!Globals.FastStartUp) {
				ClassManager.RegisterSupplySubclasses<object>(CheckViewabilityClass);
			}
		}

		/// <summary>Check if the given type is in the viewableSpecials array</summary>
		internal static bool IsViewableSpecial(Type type) {
			foreach (var specType in viewableSpecials) {
				if (specType.IsAssignableFrom(type)) {//specialViewable type is some kind of parent fo the checked type
					return true;
				}
			}
			return false;
		}

		/// <summary>
		/// Method for checking if the given Type is Viewable. If so, put it to the list.
		/// Used as hooked delegate in ClassManager
		/// </summary>
		public static bool CheckViewabilityClass(Type type) {
			//look if the type has this attribute, don't look to parent classes 
			//(if the type has not the attribute but some parent has, we dont care - if we want
			//it to be infoized, we must add a ViewableClass attribute to it)
			if (Attribute.IsDefined(type, typeof(ViewableClassAttribute), false) ||
							IsViewableSpecial(type)) {
				TryAddAsViewable(type);
			} else if (Attribute.IsDefined(type, typeof(ViewDescriptorAttribute), false)) {
				var descHandledType = ((ViewDescriptorAttribute) type.GetCustomAttributes(typeof(ViewDescriptorAttribute), false)[0]).HandledType;
				TryAddAsViewable(descHandledType);
				List<Type> descriptors;
				if (viewableDescriptorsForTypes.TryGetValue(descHandledType, out descriptors)) {
					descriptors.Add(type); //new descriptor to the list
				} else {
					descriptors = new List<Type>();
					descriptors.Add(type);
					viewableDescriptorsForTypes.Add(descHandledType, descriptors); //we have found some descriptor class
				}
			}
			return false;
		}

		private static void TryAddAsViewable(Type type) {
			if (!viewableClasses.Contains(type)) {
				viewableClasses.Add(type);
			}
		}

		/// <summary>Go through all descriptors and look if their handled type is assignable from the just generated one</summary>
		private static List<Type> FindDescriptorsForType(Type infoizedType) {
			var typeList = new List<Type>();
			var retList = new List<Type>();
			foreach (var describedType in viewableDescriptorsForTypes.Keys) {
				if (describedType.IsAssignableFrom(infoizedType)) {
					//a describedType is some parent class of the infoized type
					typeList.Add(describedType);//the described types list will be sorted and then used for getting and generating all descriptors
				}
			}
			typeList.Sort(TypeHierarchyComparer.instance);
			//now take the types that are assignable from the infoized type and get their descriptors in the right order
			foreach (var assignableTypeWithDescriptorList in typeList) {
				retList.AddRange(viewableDescriptorsForTypes[assignableTypeWithDescriptorList]);
			}
			return retList;
		}

		public static PropertyInfo GetPropertyBaseDefinition(PropertyInfo propertyInfo) {
			var method = propertyInfo.GetAccessors(true)[0];
			if (method == null)
				return null;

			var baseMethod = MemberWrapper.GetMIBaseDefinition(method);

			//if (baseMethod.ReflectedType == propertyInfo.ReflectedType)
			//    return propertyInfo;

			var allProperties = BindingFlags.Instance | BindingFlags.Public
				| BindingFlags.NonPublic | BindingFlags.Static;

			var parInfAr = propertyInfo.GetIndexParameters();
			var parTypAr = new Type[parInfAr.Length];
			for (var i = 0; i < parInfAr.Length; i++) {
				parTypAr[i] = parInfAr[i].ParameterType;
			}

			return baseMethod.DeclaringType.GetProperty(propertyInfo.Name, allProperties,
				null, propertyInfo.PropertyType, parTypAr, null);
		}

		public static FieldInfo GetFieldBaseDefinition(FieldInfo fieldInfo) {
			if (fieldInfo.DeclaringType == fieldInfo.ReflectedType) {
				return fieldInfo;
			}

			var fi = fieldInfo.DeclaringType.GetField(fieldInfo.Name, BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static);
			if (fi == null) {
				throw new FatalException("pruser");
			}
			return fi;
		}


		private class GeneratedInstance {
			//all fields except marked as NoShow
			internal Dictionary<string, FieldInfo> fields = new Dictionary<string, FieldInfo>(StringComparer.OrdinalIgnoreCase);
			internal Dictionary<string, PropertyInfo> properties = new Dictionary<string, PropertyInfo>(StringComparer.OrdinalIgnoreCase);
			internal List<MethodInfo> buttonMethods = new List<MethodInfo>();

			//member-infos that can be inherited - we wont generate a new class for them but just use the one generated on a parental viewclass
			internal HashSet<MemberInfo> inheritedInfos = new HashSet<MemberInfo>();
			//names of generated classes for buttons/fields/properties associated to the respective members
			internal Dictionary<MemberInfo, string> ownInfos = new Dictionary<MemberInfo, string>();
			internal Dictionary<PropertyMethods, string> ownPropmeths = new Dictionary<PropertyMethods, string>(); //PropertyMethods from  descriptors in a simillar way...


			HashSet<DescriptorData> descriptors = new HashSet<DescriptorData>();//all descriptors will be here
			internal HashSet<DescriptorData> inheritedDescriptors = new HashSet<DescriptorData>();//DescriptorData that neednt be generated again (will be inherited)

			HashSet<string> nonGeneratedFields = new HashSet<string>();//set of fields that will be ommited during generating (filled from descriptors)

			internal Type type; //type of the viewable class
			string typeLabel; //label for info dialogs - obtained from ViewableClassAttribute
			CodeTypeDeclaration codeTypeDeclaration;

			string generatedClassName; //name of the generated class (source code)
			GeneratedInstance parentGI;

			internal GeneratedInstance(Type type) {
				this.type = type;
				var vcaArray = type.GetCustomAttributes(typeof(ViewableClassAttribute), false);
				ViewableClassAttribute vca = null;
				if (vcaArray.Length > 0) {
					//we have the ViewableClassAttribute, get it now
					vca = (ViewableClassAttribute) vcaArray[0];
				}
				//the vca needn't be present - if the type is kind of "viewableSpecial" then the class might be without this attribute...
				this.typeLabel = ((vca == null || vca.Name == null) ? type.Name : vca.Name); //label will be either the name of the type or specified label
				//binding flags for members of the actual type - do not consider members from the possible parent classes
				var forActualMembers = BindingFlags.IgnoreCase | BindingFlags.Instance | BindingFlags.Public | BindingFlags.DeclaredOnly;
				var forInheritedMembers = BindingFlags.IgnoreCase | BindingFlags.Instance | BindingFlags.Public;

				//now find any possible descriptors, we will have to add them too...
				var typeDescriptors = FindDescriptorsForType(type);
				foreach (var descriptorType in typeDescriptors) {
					//add a prepared DescriptorData class to the list
					var descData = new DescriptorData(descriptorType);
					this.descriptors.Add(descData);
					if (descData.nonDisplayedFields != null && descData.nonDisplayedFields.Length > 0) {
						foreach (var namedField in descData.nonDisplayedFields) {
							this.nonGeneratedFields.Add(namedField);
						}
					}
				}

				//get all fields from the actual Type except for those marked as "NoShow"
				var fldsMine = type.FindMembers(MemberTypes.Field | MemberTypes.Property, forActualMembers, HasntAttribute, typeof(NoShowAttribute));
				foreach (var fld in fldsMine) {
					var propinf = fld as PropertyInfo;
					//check also if it wasn't ommited by descriptor...
					if (propinf != null && !this.nonGeneratedFields.Contains(propinf.Name)) {
						this.properties.Add(propinf.Name, GetPropertyBaseDefinition(propinf));
					}
					var fldinf = fld as FieldInfo;
					//check also if it wasn't ommited by descriptor...
					if (fldinf != null && !this.nonGeneratedFields.Contains(fldinf.Name)) {
						this.fields.Add(fldinf.Name, GetFieldBaseDefinition(fldinf));
					}
				}
				//now get the fields from the whole hierarchy, but before adding them, check if they are not present in the set (which would mean
				//that we dont want to add it (this would overwrite the membere from the actual Type by the member from parent class with the same name)
				var fldsAll = type.FindMembers(MemberTypes.Field | MemberTypes.Property, forInheritedMembers, HasntAttribute, typeof(NoShowAttribute));
				foreach (var fld in fldsAll) {
					var propinf = fld as PropertyInfo;
					//check also if it wasn't ommited by descriptor...					
					if (propinf != null && !this.nonGeneratedFields.Contains(propinf.Name)) {
						if (!this.properties.ContainsKey(propinf.Name))//isnt this property already in the dictionary?
							this.properties.Add(propinf.Name, GetPropertyBaseDefinition(propinf));
					}
					var fldinf = fld as FieldInfo;
					//check also if it wasn't ommited by descriptor...					
					if (fldinf != null && !this.nonGeneratedFields.Contains(fldinf.Name)) {
						if (!this.fields.ContainsKey(fldinf.Name))//isnt this property already in the dictionary?
							this.fields.Add(fldinf.Name, GetFieldBaseDefinition(fldinf));
					}
				}

				//get all methods from the Type that have the "Button" attribute
				var mths = type.FindMembers(MemberTypes.Method, forInheritedMembers, HasAttribute, typeof(ButtonAttribute));
				foreach (var mi in mths) {
					var minf = mi as MethodInfo;
					if (minf != null) {
						this.buttonMethods.Add(MemberWrapper.GetMIBaseDefinition(minf));
					}
				}

				this.generatedClassName = "GeneratedDataView_" + this.type.Name + "_" + classCounter++;
				this.codeTypeDeclaration = new CodeTypeDeclaration(this.generatedClassName);
			}

			internal void SetHierarchy() {
				this.parentGI = this.GetParentGI();
				if (this.parentGI != null) {
					//first check descriptor data from parents
					foreach (var oneParentDesc in this.parentGI.descriptors) {
						if (this.descriptors.Contains(oneParentDesc)) { //descriptor data will be generated on parent
							this.inheritedDescriptors.Add(oneParentDesc);
						}
					}

					//remove all fields/properties/buttons that will be generated on parent (they needn't be duplicated)
					foreach (var parentsFieldKey in this.parentGI.fields.Keys) {
						if (this.fields.ContainsKey(parentsFieldKey)) { //field will be generated on parent
							this.inheritedInfos.Add(this.fields[parentsFieldKey]);
						}
					}
					foreach (var parentsPropertyKVP in this.parentGI.properties) {
						if (this.properties.ContainsKey(parentsPropertyKVP.Key)) { //property will be generated on parent
							//if both properties are declared on the same type then consider it as "inherited" (e.g. NPC does not contain Flag_Dead so this 
							//property comes from Character but since it exists on the Character (and will be generated there) we do not need to generate it again
							//on NPC
							if (parentsPropertyKVP.Value.DeclaringType == this.properties[parentsPropertyKVP.Key].DeclaringType) {
								//if (parentsPropertyKVP.Value.GetAccessors(true)[0].IsVirtual) {
								this.inheritedInfos.Add(this.properties[parentsPropertyKVP.Key]);
								//}
							}
						}
					}
					foreach (var parentsBtnMethod in this.parentGI.buttonMethods) {
						if (this.buttonMethods.Contains(parentsBtnMethod)) { //property will be generated on parent
							//if modifier 'new' is present then the Property should not be inherited
							//e.g. - NPCDef and the property TypeDef...
							if (parentsBtnMethod.IsVirtual) {
								this.inheritedInfos.Add(parentsBtnMethod);
							}
						}
					}
				}

				//now go through the list of descriptors and add all fields and buttons originating from the descriptor too...
				//we go through the descriptors first as we want their fields to be the first on the page
				foreach (var oneDesc in this.descriptors) {
					if (!this.inheritedDescriptors.Contains(oneDesc)) {
						//first, add classes for descriptor's buttons
						foreach (var buttonMethod in oneDesc.buttonMethods) {
							var oneButtonIDFW = oneDesc.GenerateButtonIDFW(buttonMethod);
							//buttonDataFieldViews.Add(oneButtonIDFW.Name); //store the name of the new generated type
							this.codeTypeDeclaration.Members.Add(oneButtonIDFW);
							this.ownInfos[buttonMethod] = oneButtonIDFW.Name; //store name of the newly generated class
						}

						//now the descriptor's fields...
						foreach (var oneKVP in oneDesc.describedFields) {
							var oneFieldIDFW = oneDesc.GenerateFieldIDFW(oneKVP.Value);
							//fieldsDataFieldViews.Add(oneFieldIDFW.Name); //store the name of the newly generated type. use the field name as key
							this.codeTypeDeclaration.Members.Add(oneFieldIDFW);
							this.ownPropmeths[oneKVP.Value] = oneFieldIDFW.Name; //store name of the newly generated class
						}
					}
				}

				//now create the inner classes of all own IDataFieldViews for this class
				//first classes for buttons
				foreach (var buttonMethod in this.buttonMethods) {
					if (!this.inheritedInfos.Contains(buttonMethod)) { //field not inherited, must be generated here
						var oneButtonIDFW = this.GenerateButtonIDFW(buttonMethod);
						//buttonDataFieldViews.Add(oneButtonIDFW.Name); //store the name of the new generated type
						this.codeTypeDeclaration.Members.Add(oneButtonIDFW);
						this.ownInfos[buttonMethod] = oneButtonIDFW.Name; //store name of the newly generated class
					}
				}
				//then classes for datafields
				foreach (var oneField in this.fields.Values) {
					if (!this.inheritedInfos.Contains(oneField)) { //field not inherited, must be generated here
						var oneFieldIDFW = this.GenerateFieldIDFW(oneField);
						//fieldsDataFieldViews.Add(oneFieldIDFW.Name); //store the name of the new generated type
						this.codeTypeDeclaration.Members.Add(oneFieldIDFW);
						this.ownInfos[oneField] = oneFieldIDFW.Name; //store name of the newly generated class
					}
				}
				foreach (var oneProperty in this.properties.Values) {
					if (!this.inheritedInfos.Contains(oneProperty)) { //field not inherited, must be generated here
						var onePropertyIDFW = this.GenerateFieldIDFW(oneProperty);
						//fieldsDataFieldViews.Add(onePropertyIDFW.Name); //store the name of the new generated type
						this.codeTypeDeclaration.Members.Add(onePropertyIDFW);
						this.ownInfos[oneProperty] = onePropertyIDFW.Name; //store name of the newly generated class
					}
				}
			}

			internal GeneratedInstance GetParentGI() {
				var nearestParent = this.type.BaseType;
				while (nearestParent != typeof(object)) {
					GeneratedInstance parentGI = null;
					if (generatedClasses.TryGetValue(nearestParent, out parentGI)) { //check if parental class has also a GeneratedInstance
						//direct parent has no generated view class, try another parent
						return parentGI;
					}
					nearestParent = nearestParent.BaseType;
				}
				return null;
			}

			#region Viewable class' DataView generating methods
			internal CodeTypeDeclaration GetGeneratedType() {
				this.codeTypeDeclaration.TypeAttributes = TypeAttributes.Public;
				if (this.parentGI == null) {
					this.codeTypeDeclaration.BaseTypes.Add(typeof(ViewableClassDataView)); //default parent class name
				} else {
					this.codeTypeDeclaration.BaseTypes.Add(this.parentGI.generatedClassName); //inheritance between generated classes
				}
				this.codeTypeDeclaration.IsClass = true;

				//first add two methods for getting the ActionsButtonsPage and DataFieldsPage
				this.codeTypeDeclaration.Members.Add(this.GenerateGetActionButtonsPageMethod());
				this.codeTypeDeclaration.Members.Add(this.GenerateGetDataFieldsPageMethod());

				this.codeTypeDeclaration.Members.Add(this.GenerateGetActionButtonsCountMethod());
				this.codeTypeDeclaration.Members.Add(this.GenerateGetFieldsCountMethod());
				this.codeTypeDeclaration.Members.Add(this.GenerateGetNameMethod());
				this.codeTypeDeclaration.Members.Add(this.GenerateHandledTypeProperty());

				//preapre the fields and actionbuttons storages
				var buttonDataFieldViews = new List<string>();
				var fieldsDataFieldViews = new List<string>();

				//now go through the list of descriptors and add all fields and buttons originating from the descriptor too...
				//we go through the descriptors first as we want their fields to be the first on the page
				foreach (var oneDesc in this.descriptors) {
					if (!this.inheritedDescriptors.Contains(oneDesc)) {
						//first, add classes for descriptor's buttons
						foreach (var buttonMethod in oneDesc.buttonMethods) {
							buttonDataFieldViews.Add(this.ownInfos[buttonMethod]); //store the name of the new generated type
						}

						//now the descriptor's fields...
						foreach (var oneKVP in oneDesc.describedFields) {
							fieldsDataFieldViews.Add(this.ownPropmeths[oneKVP.Value]); //store the name of the new generated type
						}
					} else { //descriptor is inherited from parent - use the parent's descriptor info
						//first, add classes for descriptor's buttons
						foreach (var buttonMethod in oneDesc.buttonMethods) {
							var gi = this.parentGI;
							while (true) {
								string name;
								if (gi.ownInfos.TryGetValue(buttonMethod, out name)) {
									buttonDataFieldViews.Add(name);//if the field is also on parent, store the name from the parent's field
									break;
								}
								gi = gi.parentGI;
							}
						}

						//now the descriptor's fields...
						foreach (var oneKVP in oneDesc.describedFields) {
							var gi = this.parentGI;
							while (true) {
								string name;
								if (gi.ownPropmeths.TryGetValue(oneKVP.Value, out name)) {
									fieldsDataFieldViews.Add(name);//if the field is also on parent, store the name from the parent's field
									break;
								}
								gi = gi.parentGI;
							}
						}
					}
				}

				//first classes for buttons
				foreach (var buttonMethod in this.buttonMethods) {
					if (!this.inheritedInfos.Contains(buttonMethod)) { //field not inherited, must be generated here
						buttonDataFieldViews.Add(this.ownInfos[buttonMethod]); //store the name of the new generated type
					} else {
						var gi = this.parentGI;
						while (true) {
							string name;
							if (gi.ownInfos.TryGetValue(buttonMethod, out name)) {
								buttonDataFieldViews.Add(name);//if the field is also on parent, store the name from the parent's field
								break;
							}
							gi = gi.parentGI;
						}
					}
				}
				//then classes for datafields
				foreach (var oneField in this.fields.Values) {
					if (!this.inheritedInfos.Contains(oneField)) { //field not inherited, must be generated here
						fieldsDataFieldViews.Add(this.ownInfos[oneField]); //store the name of the new generated type
					} else {
						var gi = this.parentGI;
						while (true) {
							string name;
							if (gi.ownInfos.TryGetValue(oneField, out name)) {
								fieldsDataFieldViews.Add(name);//if the field is also on parent, store the name from the parent's field
								break;
							}
							gi = gi.parentGI;
						}
					}
				}

				foreach (var oneProperty in this.properties.Values) {
					if (!this.inheritedInfos.Contains(oneProperty)) { //field not inherited, must be generated here
						fieldsDataFieldViews.Add(this.ownInfos[oneProperty]); //store the name of the new generated type
					} else {
						var gi = this.parentGI;
						while (true) {//can happen that there is no parent left ...
							string name;
							if (gi.ownInfos.TryGetValue(oneProperty, out name)) {
								fieldsDataFieldViews.Add(name);//if the field is also on parent, store the name from the parent's field
								break;
							}
							gi = gi.parentGI;
						}
					}
				}

				//now add a Class representing one Page of action buttons
				this.codeTypeDeclaration.Members.Add(this.GenerateActionButtonsPage(buttonDataFieldViews));
				//and a Class representing one Page of other datafields
				this.codeTypeDeclaration.Members.Add(this.GenerateDataFieldsPage(fieldsDataFieldViews));

				return this.codeTypeDeclaration;
			}

			/// <summary>Method for getting one page of action buttons</summary>
			private CodeMemberMethod GenerateGetActionButtonsPageMethod() {
				var retVal = new CodeMemberMethod();
				retVal.Attributes = MemberAttributes.Public | MemberAttributes.Override;
				retVal.Name = "GetActionButtonsPage";
				retVal.Parameters.Add(new CodeParameterDeclarationExpression(typeof(int), "firstLineIndex"));
				retVal.Parameters.Add(new CodeParameterDeclarationExpression(typeof(object), "target"));
				retVal.ReturnType = new CodeTypeReference(typeof(IEnumerable<ButtonDataFieldView>));

				retVal.Statements.Add(new CodeMethodReturnStatement(
					//makes the "new ..." section
										new CodeObjectCreateExpression(this.type.Name + "ActionButtonsPage",
					//two parameters
											new CodeVariableReferenceExpression("firstLineIndex"),
											new CodeVariableReferenceExpression("target"))
										));
				return retVal;
			}

			/// <summary>Method for getting one page of data fields buttons</summary>
			private CodeMemberMethod GenerateGetDataFieldsPageMethod() {
				var retVal = new CodeMemberMethod();
				retVal.Attributes = MemberAttributes.Public | MemberAttributes.Override;
				retVal.Name = "GetDataFieldsPage";
				retVal.Parameters.Add(new CodeParameterDeclarationExpression(typeof(int), "firstLineIndex"));
				retVal.Parameters.Add(new CodeParameterDeclarationExpression(typeof(object), "target"));
				retVal.ReturnType = new CodeTypeReference(typeof(IEnumerable<IDataFieldView>));

				retVal.Statements.Add(new CodeMethodReturnStatement(
										new CodeObjectCreateExpression(this.type.Name + "DataFieldsPage",
											new CodeVariableReferenceExpression("firstLineIndex"),
											new CodeVariableReferenceExpression("target"))
										));
				return retVal;
			}

			/// <summary>The GetActionButtonsCount method - says how many buttons will there be</summary>
			private CodeMemberMethod GenerateGetActionButtonsCountMethod() {
				var buttonsCount = 0;
				buttonsCount += this.buttonMethods.Count; //class' own buttons
				foreach (var desc in this.descriptors) {
					buttonsCount += desc.buttonMethods.Count; //plus descriptor's buttons...
				}

				var retVal = new CodeMemberMethod();
				retVal.Attributes = MemberAttributes.Public | MemberAttributes.Override;
				retVal.Name = "GetActionButtonsCount";
				retVal.Parameters.Add(new CodeParameterDeclarationExpression(typeof(object), "instance"));
				retVal.ReturnType = new CodeTypeReference(typeof(int));
				retVal.Statements.Add(new CodeMethodReturnStatement(
											new CodePrimitiveExpression(
												buttonsCount
										)));
				return retVal;
			}

			/// <summary>The GenerateGetFieldsCountMethod method - says how many fields will there be</summary>
			private CodeMemberMethod GenerateGetFieldsCountMethod() {
				var fieldsCount = 0;
				fieldsCount += this.fields.Count + this.properties.Count; //class' own fields
				foreach (var desc in this.descriptors) {
					fieldsCount += desc.describedFields.Count; //plus descriptor's fields...
				}

				var retVal = new CodeMemberMethod();
				retVal.Attributes = MemberAttributes.Public | MemberAttributes.Override;
				retVal.Name = "GetFieldsCount";
				retVal.Parameters.Add(new CodeParameterDeclarationExpression(typeof(object), "instance"));
				retVal.ReturnType = new CodeTypeReference(typeof(int));
				retVal.Statements.Add(new CodeMethodReturnStatement(
											new CodePrimitiveExpression(
												fieldsCount
										)));
				return retVal;
			}

			/// <summary>The GetName method</summary>
			private CodeMemberMethod GenerateGetNameMethod() {
				var retVal = new CodeMemberMethod();
				retVal.Attributes = MemberAttributes.Public | MemberAttributes.Override;
				retVal.Name = "GetName";
				retVal.Parameters.Add(new CodeParameterDeclarationExpression(typeof(object), "instance"));
				retVal.ReturnType = new CodeTypeReference(typeof(string));
				retVal.Statements.Add(new CodeMethodReturnStatement(
											new CodePrimitiveExpression(this.typeLabel
										)));
				return retVal;
			}

			/// <summary>The HandledType getter</summary>
			private CodeMemberProperty GenerateHandledTypeProperty() {
				var retVal = new CodeMemberProperty();
				retVal.HasGet = true;
				retVal.Attributes = MemberAttributes.Public | MemberAttributes.Override;
				retVal.Name = "HandledType";
				retVal.Type = new CodeTypeReference(typeof(Type));
				retVal.GetStatements.Add(new CodeMethodReturnStatement(
											new CodeTypeOfExpression(this.type)
										));
				return retVal;
			}

			/// <summary>Generate an inner class for handling Action Buttons</summary>
			private CodeTypeDeclaration GenerateButtonIDFW(MethodInfo minf) {
				var bat = (ButtonAttribute) minf.GetCustomAttributes(typeof(ButtonAttribute), false)[0];
				var buttonLabel = (bat.Name == null ? minf.Name : bat.Name); //label of the button (could have been specified in ButtonAttribute)
				var newClassName = "GeneratedButtonDataFieldView_" + this.type.Name + "_" + minf.Name + "_" + classCounter++;
				var retVal = new CodeTypeDeclaration(newClassName);
				retVal.TypeAttributes = TypeAttributes.Public | TypeAttributes.Sealed;
				retVal.BaseTypes.Add(typeof(ButtonDataFieldView));
				retVal.IsClass = true;

				//reference to instance
				var instField = new CodeMemberField(newClassName, "instance");
				instField.Attributes = MemberAttributes.Public | MemberAttributes.Static;
				retVal.Members.Add(instField);
				//constructor
				var constr = new CodeTypeConstructor();
				constr.Attributes = MemberAttributes.Static;
				//add initialization of instance variable to the constructor
				constr.Statements.Add(new CodeAssignStatement(
										new CodeFieldReferenceExpression(new CodeTypeReferenceExpression(newClassName), "instance"),
										new CodeObjectCreateExpression(newClassName)));
				retVal.Members.Add(constr);

				//now override the Name method
				var getNameMethod = new CodeMemberMethod();
				getNameMethod.Attributes = MemberAttributes.Public | MemberAttributes.Override;
				getNameMethod.Name = "GetName";
				getNameMethod.Parameters.Add(new CodeParameterDeclarationExpression(typeof(object), "target"));
				getNameMethod.ReturnType = new CodeTypeReference(typeof(string));
				getNameMethod.Statements.Add(new CodeMethodReturnStatement(
											new CodePrimitiveExpression(
												buttonLabel
										)));
				retVal.Members.Add(getNameMethod);

				//and finally add the implementation of OnButton method
				var onButtonMeth = new CodeMemberMethod();
				onButtonMeth.Attributes = MemberAttributes.Public | MemberAttributes.Override;
				onButtonMeth.Name = "OnButton";
				onButtonMeth.ReturnType = new CodeTypeReference(typeof(void));
				onButtonMeth.Parameters.Add(new CodeParameterDeclarationExpression(typeof(object), "target"));
				onButtonMeth.Statements.Add(new CodeMethodInvokeExpression(
					//cast the "target" to the "type" and call the method referenced by the MethodMember
												new CodeCastExpression(this.type, new CodeVariableReferenceExpression("target")),
												minf.Name
											));
				retVal.Members.Add(onButtonMeth);
				return retVal;
			}

			/// <summary>Generate an inner class for handling ReadWriteData fields</summary>
			private CodeTypeDeclaration GenerateFieldIDFW(MemberInfo minf) {
				var isReadOnly = false;
				if (minf is PropertyInfo) {
					isReadOnly = !((PropertyInfo) minf).CanWrite;
					var setMethod = ((PropertyInfo) minf).GetSetMethod(true);
					if (setMethod != null) //we have the set Method - check if it is public...
						isReadOnly = !((setMethod.Attributes & MethodAttributes.Public) == MethodAttributes.Public);
				} else { //field
					isReadOnly = ((FieldInfo) minf).IsInitOnly;
				}

				Type baseAbstractClass;
				if (isReadOnly) {
					baseAbstractClass = typeof(ReadOnlyDataFieldView);
				} else {
					baseAbstractClass = typeof(ReadWriteDataFieldView);
				}

				var newClassName = "Generated" + baseAbstractClass.Name + "_" + this.type.Name + "_" + minf.Name + "_" + classCounter++;
				var retVal = new CodeTypeDeclaration(newClassName);
				retVal.TypeAttributes = TypeAttributes.Public | TypeAttributes.Sealed;
				retVal.BaseTypes.Add(baseAbstractClass);
				retVal.IsClass = true;

				//reference to instance
				var instField = new CodeMemberField(newClassName, "instance");
				instField.Attributes = MemberAttributes.Public | MemberAttributes.Static;
				retVal.Members.Add(instField);
				//constructor
				var constr = new CodeTypeConstructor();
				constr.Attributes = MemberAttributes.Static;
				//add initialization of instance variable to the constructor
				constr.Statements.Add(new CodeAssignStatement(
										new CodeFieldReferenceExpression(new CodeTypeReferenceExpression(newClassName), "instance"),
										new CodeObjectCreateExpression(newClassName)
									  ));
				retVal.Members.Add(constr);

				//now override the Name method
				//first look if the field has the InfoField attribute (it would contain its special name)
				string fieldName;
				var ifa = (InfoFieldAttribute) Attribute.GetCustomAttribute(minf, typeof(InfoFieldAttribute));
				if (ifa != null) {
					fieldName = ifa.Name;
				} else {
					fieldName = minf.Name;
				}
				var getNameMethod = new CodeMemberMethod();
				getNameMethod.Attributes = MemberAttributes.Public | MemberAttributes.Override;
				getNameMethod.Name = "GetName";
				getNameMethod.Parameters.Add(new CodeParameterDeclarationExpression(typeof(object), "target"));
				getNameMethod.ReturnType = new CodeTypeReference(typeof(string));
				getNameMethod.Statements.Add(new CodeMethodReturnStatement(
											new CodePrimitiveExpression(
												fieldName
										)));
				retVal.Members.Add(getNameMethod);

				//GetValue method
				var getValueMeth = new CodeMemberMethod();
				getValueMeth.Attributes = MemberAttributes.Public | MemberAttributes.Override;
				getValueMeth.Name = "GetValue";
				getValueMeth.ReturnType = new CodeTypeReference(typeof(object));
				getValueMeth.Parameters.Add(new CodeParameterDeclarationExpression(typeof(object), "target"));
				getValueMeth.Statements.Add(new CodeMethodReturnStatement(
												new CodeFieldReferenceExpression(
					//cast the "target" to the "type" and call the method referenced by the MethodMember
													new CodeCastExpression(this.type, new CodeVariableReferenceExpression("target")),
													minf.Name
											)));
				retVal.Members.Add(getValueMeth);

				//GetStringValue method
				var getStringValueMeth = new CodeMemberMethod();
				getStringValueMeth.Attributes = MemberAttributes.Public | MemberAttributes.Override;
				getStringValueMeth.Name = "GetStringValue";
				getStringValueMeth.ReturnType = new CodeTypeReference(typeof(string));
				getStringValueMeth.Parameters.Add(new CodeParameterDeclarationExpression(typeof(object), "target"));
				//add something like this: return ObjectSaver.Save(((SimpleClass)target).foo);
				getStringValueMeth.Statements.Add(new CodeMethodReturnStatement(
													new CodeMethodInvokeExpression(
														new CodeTypeReferenceExpression(typeof(ObjectSaver)),
														"Save",
														new CodeFieldReferenceExpression(
															new CodeCastExpression(this.type, new CodeVariableReferenceExpression("target")),
															minf.Name)
												 )));
				retVal.Members.Add(getStringValueMeth);

				Type memberType = null;
				if (minf is PropertyInfo)
					memberType = ((PropertyInfo) minf).PropertyType;
				else if (minf is FieldInfo)
					memberType = ((FieldInfo) minf).FieldType;

				if (!isReadOnly) {
					//SetValue method
					var setValueMeth = new CodeMemberMethod();
					setValueMeth.Attributes = MemberAttributes.Public | MemberAttributes.Override;
					setValueMeth.Name = "SetValue";
					setValueMeth.ReturnType = new CodeTypeReference(typeof(void));
					setValueMeth.Parameters.Add(new CodeParameterDeclarationExpression(typeof(object), "target"));
					setValueMeth.Parameters.Add(new CodeParameterDeclarationExpression(typeof(object), "value"));
					//add something like this: ((SimpleClass)target).foo = (string)value;
					setValueMeth.Statements.Add(new CodeAssignStatement(
													new CodeFieldReferenceExpression(
														new CodeCastExpression(this.type, new CodeVariableReferenceExpression("target")),
														minf.Name),
													new CodeCastExpression(memberType, new CodeVariableReferenceExpression("value"))
												));
					retVal.Members.Add(setValueMeth);

					//SetStringValue method
					var setStringValueMeth = new CodeMemberMethod();
					setStringValueMeth.Attributes = MemberAttributes.Public | MemberAttributes.Override;
					setStringValueMeth.Name = "SetStringValue";
					setStringValueMeth.ReturnType = new CodeTypeReference(typeof(void));
					setStringValueMeth.Parameters.Add(new CodeParameterDeclarationExpression(typeof(object), "target"));
					setStringValueMeth.Parameters.Add(new CodeParameterDeclarationExpression(typeof(string), "value"));
					//add something like this: ((SimpleClass)target).foo = (string)ObjectSaver.OptimizedLoad_String(value);
					setStringValueMeth.Statements.Add(new CodeAssignStatement(
														new CodeFieldReferenceExpression(
															new CodeCastExpression(this.type, new CodeVariableReferenceExpression("target")),
															minf.Name),
														GeneratedCodeUtil.GenerateSimpleLoadExpression(memberType, new CodeVariableReferenceExpression("value"))
														));
					retVal.Members.Add(setStringValueMeth);
				}

				//override the FieldType property
				var fieldTypeProp = new CodeMemberProperty();
				fieldTypeProp.HasGet = true;
				fieldTypeProp.Attributes = MemberAttributes.Public | MemberAttributes.Override;
				fieldTypeProp.Name = "FieldType";
				fieldTypeProp.Type = new CodeTypeReference(typeof(Type));
				fieldTypeProp.GetStatements.Add(new CodeMethodReturnStatement(
											new CodeTypeOfExpression(memberType)
										   ));
				retVal.Members.Add(fieldTypeProp);

				return retVal;
			}

			/// <summary>Generate a class representing an ActionButtonsPage</summary>
			private CodeTypeDeclaration GenerateActionButtonsPage(List<string> buttonDFVs) {
				var newClassName = this.type.Name + "ActionButtonsPage";
				var retVal = new CodeTypeDeclaration(newClassName);
				retVal.TypeAttributes = TypeAttributes.Public | TypeAttributes.Sealed;
				retVal.BaseTypes.Add(typeof(ViewableClassDataView.AbstractPage<ButtonDataFieldView>));
				retVal.IsClass = true;

				//constructor with two parameters (calling the base(,))
				var constr = new CodeConstructor();
				constr.Attributes = MemberAttributes.Public;
				constr.Parameters.Add(new CodeParameterDeclarationExpression(typeof(int), "firstLineIndex"));
				constr.Parameters.Add(new CodeParameterDeclarationExpression(typeof(object), "target"));
				constr.BaseConstructorArgs.Add(new CodeVariableReferenceExpression("firstLineIndex"));
				constr.BaseConstructorArgs.Add(new CodeVariableReferenceExpression("target"));
				retVal.Members.Add(constr);

				//add the MoveNext method for iterating over the buttons
				var moveNextMeth = new CodeMemberMethod();
				moveNextMeth.Attributes = MemberAttributes.Public | MemberAttributes.Override;
				moveNextMeth.Name = "MoveNext";
				moveNextMeth.ReturnType = new CodeTypeReference(typeof(bool));
				//add something like this: 							
				/*switch(nextIndex) {						
					case 0:
						current = GeneratedButtonDataFieldView_SimpleClass_SomeMethod.instance;
						break;
					default:
						//this happens when there are not enough lines to fill the whole page
						//or if we are beginning with the index larger then the overall LinesCount 
						//(which results in the empty page and should not happen)
						return false;
				}
				++nextIndex;//prepare the index for the next round of iteration
				*/
				moveNextMeth.Statements.Add(new CodeSnippetStatement("\t\t\t\tswitch(nextIndex) {"));
				for (var i = 0; i < buttonDFVs.Count; i++) { //for every ReadWriteDataFieldView add one "case"
					moveNextMeth.Statements.Add(new CodeSnippetStatement("\t\t\t\t\tcase " + i + ":"));
					moveNextMeth.Statements.Add(new CodeAssignStatement(
									new CodeVariableReferenceExpression("current"),
									new CodeFieldReferenceExpression(
										new CodeTypeReferenceExpression(buttonDFVs[i]), "instance")
								));
					moveNextMeth.Statements.Add(new CodeSnippetStatement("\t\t\t\t\t\tbreak;"));
				}
				//default section returns false (it means we have no more cases - no more fields to display 
				moveNextMeth.Statements.Add(new CodeSnippetStatement("\t\t\t\t\tdefault:"));
				moveNextMeth.Statements.Add(new CodeMethodReturnStatement(
								new CodePrimitiveExpression(false)
							));
				moveNextMeth.Statements.Add(new CodeSnippetStatement("\t\t\t\t}"));

				if (buttonDFVs.Count > 0) { //if no buttons found, only "default part" od switch - dont show any other coe
					//increase indexer for the next step
					moveNextMeth.Statements.Add(new CodeAssignStatement(
									new CodeVariableReferenceExpression("nextIndex"),
									new CodeBinaryOperatorExpression(
										new CodeVariableReferenceExpression("nextIndex"),
										CodeBinaryOperatorType.Add,
										new CodePrimitiveExpression(1)
								)));
					//return true -we will continue in iterating
					moveNextMeth.Statements.Add(new CodeMethodReturnStatement(
									new CodePrimitiveExpression(true)
								));
				}

				retVal.Members.Add(moveNextMeth);

				return retVal;
			}

			/// <summary>Generate a class representing an DataFieldsPage</summary>
			private CodeTypeDeclaration GenerateDataFieldsPage(List<string> fieldsDFVs) {
				var newClassName = this.type.Name + "DataFieldsPage";
				var retVal = new CodeTypeDeclaration(newClassName);
				retVal.TypeAttributes = TypeAttributes.Public | TypeAttributes.Sealed;
				retVal.BaseTypes.Add(typeof(ViewableClassDataView.AbstractPage<IDataFieldView>));
				retVal.IsClass = true;

				//constructor with two parameters (calling the base(,))
				var constr = new CodeConstructor();
				constr.Attributes = MemberAttributes.Public;
				constr.Parameters.Add(new CodeParameterDeclarationExpression(typeof(int), "firstLineIndex"));
				constr.Parameters.Add(new CodeParameterDeclarationExpression(typeof(object), "target"));
				constr.BaseConstructorArgs.Add(new CodeVariableReferenceExpression("firstLineIndex"));
				constr.BaseConstructorArgs.Add(new CodeVariableReferenceExpression("target"));
				retVal.Members.Add(constr);

				//add the MoveNext method for iterating over the fields
				var moveNextMeth = new CodeMemberMethod();
				moveNextMeth.Attributes = MemberAttributes.Public | MemberAttributes.Override;
				moveNextMeth.Name = "MoveNext";
				moveNextMeth.ReturnType = new CodeTypeReference(typeof(bool));
				//add something like this: 
				/*	switch(nextIndex) {						
						case 0:
							current = GeneratedButtonDataFieldView_SimpleClass_SomeMethod.instance;
							break;
						default:
							//this happens when there are not enough lines to fill the whole page
							//or if we are beginning with the index larger then the overall LinesCount 
							//(which results in the empty page and should not happen)
							return false;
					}
					++nextIndex;//prepare the index for the next round of iteration
					return true;
				*/
				//prepare the iteration block
				//List<CodeStatement> iterationBlock = new List<CodeStatement>();

				moveNextMeth.Statements.Add(new CodeSnippetStatement("\t\t\t\tswitch(nextIndex) {"));
				for (var i = 0; i < fieldsDFVs.Count; i++) { //for every IDataFieldView add one "case"
					moveNextMeth.Statements.Add(new CodeSnippetStatement("\t\t\t\t\tcase " + i + ":"));
					moveNextMeth.Statements.Add(new CodeAssignStatement(
									new CodeVariableReferenceExpression("current"),
									new CodeFieldReferenceExpression(
										new CodeTypeReferenceExpression(fieldsDFVs[i]), "instance")
								));
					moveNextMeth.Statements.Add(new CodeSnippetStatement("\t\t\t\t\t\tbreak;"));
				}
				//default section returns false (it means we have no more cases - no more fields to display 
				moveNextMeth.Statements.Add(new CodeSnippetStatement("\t\t\t\t\tdefault:"));
				moveNextMeth.Statements.Add(new CodeMethodReturnStatement(
								new CodePrimitiveExpression(false)
							));
				moveNextMeth.Statements.Add(new CodeSnippetStatement("\t\t\t\t}"));

				if (fieldsDFVs.Count > 0) { //if no fields found, only "default part" of switch - dont show anything else
					//increase indexer for the next step
					moveNextMeth.Statements.Add(new CodeAssignStatement(
									new CodeVariableReferenceExpression("nextIndex"),
									new CodeBinaryOperatorExpression(
										new CodeVariableReferenceExpression("nextIndex"),
										CodeBinaryOperatorType.Add,
										new CodePrimitiveExpression(1)
								)));

					//return true -we will continue with iterating				
					moveNextMeth.Statements.Add(new CodeMethodReturnStatement(
									new CodePrimitiveExpression(true)
								));
				}
				retVal.Members.Add(moveNextMeth);

				return retVal;
			}

			/// <summary>Used in constructor for filtering - obtain all members with given attribute</summary>
			private static bool HasAttribute(MemberInfo m, object attributeType) {
				var attType = (Type) attributeType;
				return Attribute.IsDefined(m, attType, false);
			}

			/// <summary>Used in constructor for filtering- obtain all members except those with given attribute</summary>
			private static bool HasntAttribute(MemberInfo m, object attributeType) {
				var attType = (Type) attributeType;
				return !Attribute.IsDefined(m, attType, false);
			}
			#endregion

			internal int GetAllFieldViewsCount() {
				var retVal = 0;
				retVal = this.fields.Count + this.properties.Count + this.buttonMethods.Count;
				//add also all fields from descriptor
				foreach (var descData in this.descriptors) {
					retVal += descData.buttonMethods.Count;
					retVal += descData.describedFields.Count;
				}
				return retVal;
			}
		}

		/// <summary>
		/// Special class used similiarly as GeneratedInstance but only for ViewableDescriptors.
		/// All found descriptors will have one instance and they will be stored in a list in the GeneratedInstance class
		/// </summary>
		private class DescriptorData {
			Type handledType;
			Type descriptorType;
			string descLabel; //label for info dialogs - it will be used unless the ViewableClass for the Type is found

			//this will be the list containing all descriptor methods from which the dialog action buttons will be created
			internal List<MethodInfo> buttonMethods = new List<MethodInfo>();
			//in this dictionary will be stored all described fields. we will find out whether the field has Getter or Setter (or both) methods
			internal Dictionary<string, PropertyMethods> describedFields = new Dictionary<string, PropertyMethods>(StringComparer.OrdinalIgnoreCase);

			internal string[] nonDisplayedFields;//explicitely named fields that wont be generated to the DataView

			public override int GetHashCode() {
				return this.descriptorType.GetHashCode();
			}

			public override bool Equals(object obj) {
				var objDD = obj as DescriptorData;
				if (objDD == null) {
					return false;
				}
				return this.descriptorType.Equals(objDD.descriptorType);
			}

			internal DescriptorData(Type descriptorType) {
				this.descriptorType = descriptorType;
				var vda = (ViewDescriptorAttribute) descriptorType.GetCustomAttributes(typeof(ViewDescriptorAttribute), false)[0];
				this.descLabel = (vda.Name == null ? this.handledType.Name : vda.Name); //label will be either the name of the type or specified label
				this.handledType = vda.HandledType;
				this.nonDisplayedFields = vda.NonDisplayedFields; //can be null or array of fieldnames

				//binding flags for members of the actual type - do not consider members from the possible parent classes, everything is static here!
				var forMembers = BindingFlags.IgnoreCase | BindingFlags.Static | BindingFlags.Public;

				//get all methods from the descriptor that have the "Button" attribute
				var mths = descriptorType.FindMembers(MemberTypes.Method, forMembers, HasAttribute, typeof(ButtonAttribute));
				foreach (var mi in mths) {
					var minf = mi as MethodInfo;
					if (minf != null) {
						this.buttonMethods.Add(MemberWrapper.GetMIBaseDefinition(minf));
					}
				}

				//get all methods from the descriptor that have the "GetMethod" attribute
				mths = descriptorType.FindMembers(MemberTypes.Method, forMembers, HasAttribute, typeof(GetMethodAttribute));
				foreach (var mi in mths) {
					var minf = mi as MethodInfo;
					if (minf != null) {
						//get the name from the attribute
						var gmAtt = (GetMethodAttribute) Attribute.GetCustomAttribute(minf, typeof(GetMethodAttribute));
						var fieldName = gmAtt.Name;
						var fieldType = gmAtt.FieldType;

						//if(describedFields.ContainsKey(fieldName)) {
						//    pm = describedFields[fieldName];//get it from the dictionary
						//} else {
						//    pm = new PropertyMethods(fieldName,fieldType);
						//    describedFields.Add(fieldName, pm);//store it newly to the dictionary
						//}
						PropertyMethods pm;
						if (!this.describedFields.TryGetValue(fieldName, out pm)) {
							pm = new PropertyMethods(fieldName, fieldType);
							this.describedFields.Add(fieldName, pm);//store it newly to the dictionary
						}
						pm.GetMethod = minf;
					}
				}

				//get all methods from the Type that have the "SetMethod" attribute
				mths = descriptorType.FindMembers(MemberTypes.Method, forMembers, HasAttribute, typeof(SetMethodAttribute));
				foreach (var mi in mths) {
					var minf = mi as MethodInfo;
					if (minf != null) {
						//get the name and fieldtype from the attribute
						var smAtt = (SetMethodAttribute) Attribute.GetCustomAttribute(minf, typeof(SetMethodAttribute));
						var fieldName = smAtt.Name;
						var fieldType = smAtt.FieldType;


						//if(describedFields.ContainsKey(fieldName)) {
						//    pm = describedFields[fieldName];//get it from the dictionary
						//} else {
						//    pm = new PropertyMethods(fieldName,fieldType);
						//    describedFields.Add(fieldName, pm);//store it newly to the dictionary
						//}
						PropertyMethods pm;
						if (!this.describedFields.TryGetValue(fieldName, out pm)) {
							pm = new PropertyMethods(fieldName, fieldType);
							this.describedFields.Add(fieldName, pm);//store it newly to the dictionary
						}
						pm.SetMethod = minf;
					}
				}
			}

			#region Descriptor's fields/buttons build methods
			/// <summary>Generate an inner class for handling one descriptor's Action Button</summary>
			internal CodeTypeDeclaration GenerateButtonIDFW(MethodInfo minf) {
				var bat = (ButtonAttribute) minf.GetCustomAttributes(typeof(ButtonAttribute), false)[0];
				var buttonLabel = (bat.Name == null ? minf.Name : bat.Name); //label of the button (could have been specified in ButtonAttribute)
				var newClassName = "GeneratedButtonDataFieldView_" + this.handledType.Name + "_" + minf.Name + "_" + classCounter++;
				var retVal = new CodeTypeDeclaration(newClassName);
				retVal.TypeAttributes = TypeAttributes.Public | TypeAttributes.Sealed;
				retVal.BaseTypes.Add(typeof(ButtonDataFieldView));
				retVal.IsClass = true;

				//reference to instance
				var instField = new CodeMemberField(newClassName, "instance");
				instField.Attributes = MemberAttributes.Public | MemberAttributes.Static;
				retVal.Members.Add(instField);
				//constructor
				var constr = new CodeTypeConstructor();
				constr.Attributes = MemberAttributes.Static;
				//add initialization of instance variable to the constructor
				constr.Statements.Add(new CodeAssignStatement(
										new CodeFieldReferenceExpression(new CodeTypeReferenceExpression(newClassName), "instance"),
										new CodeObjectCreateExpression(newClassName)));
				retVal.Members.Add(constr);

				//now override the Name method
				var getNameMethod = new CodeMemberMethod();
				getNameMethod.Attributes = MemberAttributes.Public | MemberAttributes.Override;
				getNameMethod.Name = "GetName";
				getNameMethod.Parameters.Add(new CodeParameterDeclarationExpression(typeof(object), "target"));
				getNameMethod.ReturnType = new CodeTypeReference(typeof(string));
				getNameMethod.Statements.Add(new CodeMethodReturnStatement(
											new CodePrimitiveExpression(
												buttonLabel
										)));
				retVal.Members.Add(getNameMethod);

				//and finally add the implementation of OnButton method
				var onButtonMeth = new CodeMemberMethod();
				onButtonMeth.Attributes = MemberAttributes.Public | MemberAttributes.Override;
				onButtonMeth.Name = "OnButton";
				onButtonMeth.ReturnType = new CodeTypeReference(typeof(void));
				onButtonMeth.Parameters.Add(new CodeParameterDeclarationExpression(typeof(object), "target"));
				onButtonMeth.Statements.Add(new CodeMethodInvokeExpression(
					//call the static method from the Descriptor referenced by MethodInfo
												new CodeTypeReferenceExpression(this.descriptorType),
												minf.Name, new CodeVariableReferenceExpression("target")));
				retVal.Members.Add(onButtonMeth);
				return retVal;
			}

			/// <summary>Generate an inner class for handling descriptor's Read(Write/Only)Data fields</summary>
			internal CodeTypeDeclaration GenerateFieldIDFW(PropertyMethods propMeth) {
				var isReadOnly = !propMeth.HasSetMethod; //if we dont have Set method, it is readonly

				//check if we have GetMethod (if not then it is time to throw an exception...)
				//setmethod can miss but get method no!
				if (!propMeth.HasGetMethod) {
					throw new SEException("Missing GetMethod for field " + propMeth.FieldLabel + " in descriptor " + this.descriptorType.Name);
				}

				Type baseAbstractClass;
				if (isReadOnly) {
					baseAbstractClass = typeof(ReadOnlyDataFieldView);
				} else {
					baseAbstractClass = typeof(ReadWriteDataFieldView);
				}

				//classname must not contain spaces (thetrefore replace them in the field name from the attribute
				var newClassName = "Generated" + baseAbstractClass.Name + "_" + this.descriptorType.Name + "_" + propMeth.FieldLabel.Replace(' ', '_') + "_" + classCounter++;
				var retVal = new CodeTypeDeclaration(newClassName);
				retVal.TypeAttributes = TypeAttributes.Public | TypeAttributes.Sealed;
				retVal.BaseTypes.Add(baseAbstractClass);
				retVal.IsClass = true;

				//reference to instance
				var instField = new CodeMemberField(newClassName, "instance");
				instField.Attributes = MemberAttributes.Public | MemberAttributes.Static;
				retVal.Members.Add(instField);
				//constructor
				var constr = new CodeTypeConstructor();
				constr.Attributes = MemberAttributes.Static;
				//add initialization of instance variable to the constructor
				constr.Statements.Add(new CodeAssignStatement(
										new CodeFieldReferenceExpression(new CodeTypeReferenceExpression(newClassName), "instance"),
										new CodeObjectCreateExpression(newClassName)
									  ));
				retVal.Members.Add(constr);

				//now override the Name method
				var getNameMethod = new CodeMemberMethod();
				getNameMethod.Attributes = MemberAttributes.Public | MemberAttributes.Override;
				getNameMethod.Name = "GetName";
				getNameMethod.Parameters.Add(new CodeParameterDeclarationExpression(typeof(object), "target"));
				getNameMethod.ReturnType = new CodeTypeReference(typeof(string));
				getNameMethod.Statements.Add(new CodeMethodReturnStatement(
											new CodePrimitiveExpression(
												propMeth.FieldLabel
										)));
				retVal.Members.Add(getNameMethod);

				//GetValue method
				var getValueMeth = new CodeMemberMethod();
				getValueMeth.Attributes = MemberAttributes.Public | MemberAttributes.Override;
				getValueMeth.Name = "GetValue";
				getValueMeth.ReturnType = new CodeTypeReference(typeof(object));
				getValueMeth.Parameters.Add(new CodeParameterDeclarationExpression(typeof(object), "target"));
				getValueMeth.Statements.Add(new CodeMethodReturnStatement(
					//call the static method from the Descriptor referenced by PropMethods
												new CodeMethodInvokeExpression(
													new CodeTypeReferenceExpression(this.descriptorType),
														propMeth.GetMethod.Name, new CodeVariableReferenceExpression("target"))));
				retVal.Members.Add(getValueMeth);

				//GetStringValue method
				var getStringValueMeth = new CodeMemberMethod();
				getStringValueMeth.Attributes = MemberAttributes.Public | MemberAttributes.Override;
				getStringValueMeth.Name = "GetStringValue";
				getStringValueMeth.ReturnType = new CodeTypeReference(typeof(string));
				getStringValueMeth.Parameters.Add(new CodeParameterDeclarationExpression(typeof(object), "target"));
				//add something like this: return ObjectSaver.Save(<returned_value_from_the_descriptor_getmethod>);
				getStringValueMeth.Statements.Add(new CodeMethodReturnStatement(
													new CodeMethodInvokeExpression(
														new CodeTypeReferenceExpression(typeof(ObjectSaver)),
														"Save",
														new CodeMethodInvokeExpression(
																new CodeTypeReferenceExpression(this.descriptorType),
																propMeth.GetMethod.Name, new CodeVariableReferenceExpression("target")))));
				retVal.Members.Add(getStringValueMeth);

				if (!isReadOnly) {
					//SetValue method
					var setValueMeth = new CodeMemberMethod();
					setValueMeth.Attributes = MemberAttributes.Public | MemberAttributes.Override;
					setValueMeth.Name = "SetValue";
					setValueMeth.ReturnType = new CodeTypeReference(typeof(void));
					setValueMeth.Parameters.Add(new CodeParameterDeclarationExpression(typeof(object), "target"));
					setValueMeth.Parameters.Add(new CodeParameterDeclarationExpression(typeof(object), "value"));
					//add something like this: DescriptorClass.SetSomeField(target,value);
					setValueMeth.Statements.Add(new CodeMethodInvokeExpression(
														new CodeTypeReferenceExpression(this.descriptorType),
														propMeth.SetMethod.Name, new CodeVariableReferenceExpression("target"), new CodeVariableReferenceExpression("value")));
					retVal.Members.Add(setValueMeth);

					//SetStringValue method
					var setStringValueMeth = new CodeMemberMethod();
					setStringValueMeth.Attributes = MemberAttributes.Public | MemberAttributes.Override;
					setStringValueMeth.Name = "SetStringValue";
					setStringValueMeth.ReturnType = new CodeTypeReference(typeof(void));
					setStringValueMeth.Parameters.Add(new CodeParameterDeclarationExpression(typeof(object), "target"));
					setStringValueMeth.Parameters.Add(new CodeParameterDeclarationExpression(typeof(string), "value"));
					//add something like this: DescriptorClass.SetSomeFiel(target,<stringified_value>)
					setStringValueMeth.Statements.Add(new CodeMethodInvokeExpression(
														new CodeTypeReferenceExpression(this.descriptorType),
														propMeth.SetMethod.Name, new CodeVariableReferenceExpression("target"), GeneratedCodeUtil.GenerateSimpleLoadExpression(propMeth.FieldType, new CodeVariableReferenceExpression("value"))));
					retVal.Members.Add(setStringValueMeth);
				}

				//override the FieldType property
				var fieldTypeProp = new CodeMemberProperty();
				fieldTypeProp.HasGet = true;
				fieldTypeProp.Attributes = MemberAttributes.Public | MemberAttributes.Override;
				fieldTypeProp.Name = "FieldType";
				fieldTypeProp.Type = new CodeTypeReference(typeof(Type));
				fieldTypeProp.GetStatements.Add(new CodeMethodReturnStatement(
											new CodeTypeOfExpression(propMeth.FieldType)
										   ));
				retVal.Members.Add(fieldTypeProp);

				return retVal;
			}
			#endregion

			/// <summary>Used in constructor for filtering - obtain all members with given attribute</summary>
			private static bool HasAttribute(MemberInfo m, object attributeType) {
				var attType = (Type) attributeType;
				return Attribute.IsDefined(m, attType, false);
			}
		}

		/// <summary>
		/// Utility class used for holding MethodInfos of Get and Set methods from the descriptor. 
		/// Both Get and Set methods are connected with single described field
		/// </summary>
		internal class PropertyMethods {
			private MethodInfo getMethod;
			private MethodInfo setMethod;
			private string fieldLabel;
			private Type fieldType;

			internal PropertyMethods(string fieldLabel, Type fieldType) {
				this.fieldLabel = fieldLabel;
				this.fieldType = fieldType;
			}

			public override int GetHashCode() {
				return this.fieldType.GetHashCode() *this.fieldLabel.GetHashCode();
			}

			public override bool Equals(object obj) {
				var objPM = obj as PropertyMethods;
				if (objPM == null) {
					return false;
				}
				return this.fieldType.Equals(objPM.FieldType) && this.fieldLabel.Equals(objPM.FieldLabel);
			}

			internal bool HasGetMethod {
				get {
					return (this.getMethod != null);
				}
			}

			internal bool HasSetMethod {
				get {
					return (this.setMethod != null);
				}
			}

			internal string FieldLabel {
				get {
					return this.fieldLabel;
				}
				//set {
				//    fieldLabel = value;
				//}
			}

			internal Type FieldType {
				get {
					return this.fieldType;
				}
				//set {
				//    this.fieldType = value;
				//}
			}

			internal MethodInfo GetMethod {
				get {
					return this.getMethod;
				}
				set {
					this.getMethod = value;
				}
			}

			internal MethodInfo SetMethod {
				get {
					return this.setMethod;
				}
				set {
					this.setMethod = value;
				}
			}
		}
	}
}